// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type {
  GetHelloData,
  GetHelloResponses,
  PostHelloData,
  PostHelloResponses,
  CheckPgData,
  CheckPgResponses,
  CheckTokenData,
  CheckTokenResponses,
  LoginData,
  LoginResponses,
  CreateWidgetData,
  CreateWidgetResponses,
  DeleteWidgetData,
  DeleteWidgetResponses,
  GetWidgetData,
  GetWidgetResponses,
  UpdateWidgetData,
  UpdateWidgetResponses,
  RefreshWidgetData,
  RefreshWidgetResponses,
  ChatData,
  ChatResponses,
  QueryData,
  QueryResponses,
  ListDashboardsData,
  ListDashboardsResponses,
  CreateDashboardData,
  CreateDashboardResponses,
  DeleteDashboardData,
  DeleteDashboardResponses,
  GetDashboardData,
  GetDashboardResponses,
  UpdateDashboardData,
  UpdateDashboardResponses,
  CheckCredentialsData,
  CheckCredentialsResponses,
  UpdateCredentialsData,
  UpdateCredentialsResponses,
} from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const getHello = <ThrowOnError extends boolean = false>(
  options?: Options<GetHelloData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<GetHelloResponses, unknown, ThrowOnError>({
    url: '/',
    ...options,
  });
};

export const postHello = <ThrowOnError extends boolean = false>(
  options?: Options<PostHelloData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<PostHelloResponses, unknown, ThrowOnError>({
    url: '/',
    ...options,
  });
};

export const checkPg = <ThrowOnError extends boolean = false>(
  options?: Options<CheckPgData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<CheckPgResponses, unknown, ThrowOnError>({
    url: '/check_pg',
    ...options,
  });
};

export const checkToken = <ThrowOnError extends boolean = false>(
  options?: Options<CheckTokenData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<CheckTokenResponses, unknown, ThrowOnError>({
    url: '/check_token',
    ...options,
  });
};

export const login = <ThrowOnError extends boolean = false>(
  options?: Options<LoginData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<LoginResponses, unknown, ThrowOnError>({
    url: '/login',
    ...options,
  });
};

export const createWidget = <ThrowOnError extends boolean = false>(
  options: Options<CreateWidgetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<CreateWidgetResponses, unknown, ThrowOnError>({
    url: '/widget',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const deleteWidget = <ThrowOnError extends boolean = false>(
  options: Options<DeleteWidgetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<DeleteWidgetResponses, unknown, ThrowOnError>({
    url: '/widget/{widgetId}',
    ...options,
  });
};

export const getWidget = <ThrowOnError extends boolean = false>(
  options: Options<GetWidgetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<GetWidgetResponses, unknown, ThrowOnError>({
    url: '/widget/{widgetId}',
    ...options,
  });
};

export const updateWidget = <ThrowOnError extends boolean = false>(
  options: Options<UpdateWidgetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<UpdateWidgetResponses, unknown, ThrowOnError>({
    url: '/widget/{widgetId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const refreshWidget = <ThrowOnError extends boolean = false>(
  options: Options<RefreshWidgetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<RefreshWidgetResponses, unknown, ThrowOnError>({
    url: '/widget/{widgetId}/refresh',
    ...options,
  });
};

export const chat = <ThrowOnError extends boolean = false>(
  options?: Options<ChatData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<ChatResponses, unknown, ThrowOnError>({
    url: '/widget/chat',
    ...options,
  });
};

export const query = <ThrowOnError extends boolean = false>(
  options: Options<QueryData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<QueryResponses, unknown, ThrowOnError>({
    url: '/widget/query',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const listDashboards = <ThrowOnError extends boolean = false>(
  options?: Options<ListDashboardsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<ListDashboardsResponses, unknown, ThrowOnError>({
    url: '/dashboard',
    ...options,
  });
};

export const createDashboard = <ThrowOnError extends boolean = false>(
  options: Options<CreateDashboardData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<CreateDashboardResponses, unknown, ThrowOnError>({
    url: '/dashboard',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const deleteDashboard = <ThrowOnError extends boolean = false>(
  options: Options<DeleteDashboardData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<DeleteDashboardResponses, unknown, ThrowOnError>({
    url: '/dashboard/{dashboardId}',
    ...options,
  });
};

export const getDashboard = <ThrowOnError extends boolean = false>(
  options: Options<GetDashboardData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<GetDashboardResponses, unknown, ThrowOnError>({
    url: '/dashboard/{dashboardId}',
    ...options,
  });
};

export const updateDashboard = <ThrowOnError extends boolean = false>(
  options: Options<UpdateDashboardData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<UpdateDashboardResponses, unknown, ThrowOnError>({
    url: '/dashboard/{dashboardId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const checkCredentials = <ThrowOnError extends boolean = false>(
  options?: Options<CheckCredentialsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<CheckCredentialsResponses, unknown, ThrowOnError>({
    url: '/posthog',
    ...options,
  });
};

export const updateCredentials = <ThrowOnError extends boolean = false>(
  options: Options<UpdateCredentialsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<UpdateCredentialsResponses, unknown, ThrowOnError>({
    url: '/posthog',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
