// This file is auto-generated by @hey-api/openapi-ts

export type LoginResponseDto = {
  isPosthogValid: boolean;
  remainingCredits: number;
};

export type CreateWidgetDto = {
  dashboardId: string;
  type: 'line-chart' | 'number-card' | 'bar-chart' | 'data-table' | 'pie-chart' | 'funnel';
  title: string;
  size?: 'small' | 'medium' | 'large';
  query: string;
  config?: {
    [key: string]: unknown;
  };
};

export type CreateWidgetResponseDto = {
  widgetId: string;
  remainingCredits: number;
};

export type WidgetGetDto = {
  widgetId: string;
  type: string;
  title: string;
  size: string;
  query: string;
  config?: {
    [key: string]: unknown;
  };
  data?: {
    [key: string]: unknown;
  };
  createdAt: string;
  updatedAt: string;
};

export type UpdateWidgetDto = {
  type?: 'line-chart' | 'number-card' | 'bar-chart' | 'data-table' | 'pie-chart' | 'funnel';
  title?: string;
  size?: 'small' | 'medium' | 'large';
  query?: string;
  config?: {
    [key: string]: unknown;
  };
};

export type UpdateWidgetResponseDto = {
  widgetId: string;
};

export type DeleteWidgetResponseDto = {
  widgetId: string;
};

export type ChatResponseDto = {
  widget?: {
    [key: string]: unknown;
  };
  reply: string;
  threadId: string;
  remainingCredits?: number;
};

export type QueryDto = {
  query: string;
};

export type QueryResponseDto = {
  data: {
    [key: string]: unknown;
  };
};

export type CreateDashboardDto = {
  name?: string;
  description?: string;
};

export type CreateDashboardResponseDto = {
  dashboardId: string;
};

export type DashboardSummaryDto = {
  dashboardId: string;
  name: string;
  description: string | null;
  createdAt: string;
  updatedAt: string;
  widgetIds: Array<string>;
};

export type ListDashboardsResponseDto = {
  dashboards: Array<DashboardSummaryDto>;
};

export type GetDashboardResponseDto = {
  dashboardId: string;
  name: string;
  description: string | null;
  createdAt: string;
  updatedAt: string;
  isArchived?: boolean;
  widgets: Array<WidgetGetDto>;
};

export type UpdateDashboardDto = {
  name?: string;
  description?: string;
};

export type UpdateDashboardResponseDto = {
  dashboardId: string;
};

export type DeleteDashboardResponseDto = {
  dashboardId: string;
};

export type CheckPosthogResponseDto = {
  isValid: boolean;
};

export type UpdatePosthogDto = {
  posthogApiKey: string;
  posthogProjectId: string;
};

export type UpdatePosthogResponseDto = {
  userId: string;
};

export type GetHelloData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/';
};

export type GetHelloResponses = {
  200: string;
};

export type GetHelloResponse = GetHelloResponses[keyof GetHelloResponses];

export type PostHelloData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/';
};

export type PostHelloResponses = {
  201: string;
};

export type PostHelloResponse = PostHelloResponses[keyof PostHelloResponses];

export type CheckPgData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/check_pg';
};

export type CheckPgResponses = {
  200: unknown;
};

export type CheckTokenData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/check_token';
};

export type CheckTokenResponses = {
  200: {
    [key: string]: unknown;
  };
};

export type CheckTokenResponse = CheckTokenResponses[keyof CheckTokenResponses];

export type LoginData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/login';
};

export type LoginResponses = {
  201: LoginResponseDto;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type CreateWidgetData = {
  body: CreateWidgetDto;
  path?: never;
  query?: never;
  url: '/widget';
};

export type CreateWidgetResponses = {
  201: CreateWidgetResponseDto;
};

export type CreateWidgetResponse = CreateWidgetResponses[keyof CreateWidgetResponses];

export type DeleteWidgetData = {
  body?: never;
  path: {
    widgetId: string;
  };
  query?: never;
  url: '/widget/{widgetId}';
};

export type DeleteWidgetResponses = {
  200: DeleteWidgetResponseDto;
};

export type DeleteWidgetResponse = DeleteWidgetResponses[keyof DeleteWidgetResponses];

export type GetWidgetData = {
  body?: never;
  path: {
    widgetId: string;
  };
  query?: never;
  url: '/widget/{widgetId}';
};

export type GetWidgetResponses = {
  200: WidgetGetDto;
};

export type GetWidgetResponse = GetWidgetResponses[keyof GetWidgetResponses];

export type UpdateWidgetData = {
  body: UpdateWidgetDto;
  path: {
    widgetId: string;
  };
  query?: never;
  url: '/widget/{widgetId}';
};

export type UpdateWidgetResponses = {
  200: UpdateWidgetResponseDto;
};

export type UpdateWidgetResponse = UpdateWidgetResponses[keyof UpdateWidgetResponses];

export type RefreshWidgetData = {
  body?: never;
  path: {
    widgetId: string;
  };
  query?: never;
  url: '/widget/{widgetId}/refresh';
};

export type RefreshWidgetResponses = {
  201: WidgetGetDto;
};

export type RefreshWidgetResponse = RefreshWidgetResponses[keyof RefreshWidgetResponses];

export type ChatData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/widget/chat';
};

export type ChatResponses = {
  201: ChatResponseDto;
};

export type ChatResponse = ChatResponses[keyof ChatResponses];

export type QueryData = {
  body: QueryDto;
  path?: never;
  query?: never;
  url: '/widget/query';
};

export type QueryResponses = {
  201: QueryResponseDto;
};

export type QueryResponse = QueryResponses[keyof QueryResponses];

export type ListDashboardsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/dashboard';
};

export type ListDashboardsResponses = {
  200: ListDashboardsResponseDto;
};

export type ListDashboardsResponse = ListDashboardsResponses[keyof ListDashboardsResponses];

export type CreateDashboardData = {
  body: CreateDashboardDto;
  path?: never;
  query?: never;
  url: '/dashboard';
};

export type CreateDashboardResponses = {
  201: CreateDashboardResponseDto;
};

export type CreateDashboardResponse = CreateDashboardResponses[keyof CreateDashboardResponses];

export type DeleteDashboardData = {
  body?: never;
  path: {
    dashboardId: string;
  };
  query?: never;
  url: '/dashboard/{dashboardId}';
};

export type DeleteDashboardResponses = {
  200: DeleteDashboardResponseDto;
};

export type DeleteDashboardResponse = DeleteDashboardResponses[keyof DeleteDashboardResponses];

export type GetDashboardData = {
  body?: never;
  path: {
    dashboardId: string;
  };
  query?: never;
  url: '/dashboard/{dashboardId}';
};

export type GetDashboardResponses = {
  200: GetDashboardResponseDto;
};

export type GetDashboardResponse = GetDashboardResponses[keyof GetDashboardResponses];

export type UpdateDashboardData = {
  body: UpdateDashboardDto;
  path: {
    dashboardId: string;
  };
  query?: never;
  url: '/dashboard/{dashboardId}';
};

export type UpdateDashboardResponses = {
  200: UpdateDashboardResponseDto;
};

export type UpdateDashboardResponse = UpdateDashboardResponses[keyof UpdateDashboardResponses];

export type CheckCredentialsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/posthog';
};

export type CheckCredentialsResponses = {
  200: CheckPosthogResponseDto;
};

export type CheckCredentialsResponse = CheckCredentialsResponses[keyof CheckCredentialsResponses];

export type UpdateCredentialsData = {
  body: UpdatePosthogDto;
  path?: never;
  query?: never;
  url: '/posthog';
};

export type UpdateCredentialsResponses = {
  200: UpdatePosthogResponseDto;
};

export type UpdateCredentialsResponse =
  UpdateCredentialsResponses[keyof UpdateCredentialsResponses];

export type ClientOptions = {
  baseUrl: string;
};
