version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Run ESLint
          command: npm run lint
      - run:
          name: Run tests
          command: npm run test
  build:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Build Project
          command: npm run build
      - store_artifacts:
          path: .next
  deploy:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - run:
          name: Deploy Project
          command: echo 'Replace this with deployment commands'
workflows:
  version: 2
  example:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
